# Generated by Django 5.1.15 on 2026-01-17 17:30

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_te', models.CharField(blank=True, help_text='Telugu translation', max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'News Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PressRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('excerpt', models.TextField(help_text='Short summary', max_length=500)),
                ('body', wagtail.fields.RichTextField(help_text='Full article content')),
                ('title_te', models.CharField(blank=True, help_text='Telugu title', max_length=500)),
                ('excerpt_te', models.TextField(blank=True, help_text='Telugu summary', max_length=500)),
                ('body_te', wagtail.fields.RichTextField(blank=True, help_text='Telugu article content')),
                ('author', models.CharField(default='Ministry of Minority Welfare', max_length=255)),
                ('is_published', models.BooleanField(default=False, help_text='Publish this article')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('published_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views', models.PositiveIntegerField(default=0, editable=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='press_releases', to='cms.newscategory')),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Press Release / News Article',
                'verbose_name_plural': 'Press Releases / News Articles',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='PressReleaseTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='cms.pressrelease')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pressrelease',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='cms.PressReleaseTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
